version: '3'
services:
    cache:
        hostname: cache
        image: redis:4
        command: redis-server --appendonly yes
        restart: always
        ports:
            - 6379:6379

    mq:
        hostname: mq
        image: webcenter/activemq:latest
        restart: always
        ports:
            - 61616:61616
            - 61613:61613
            - 8161:8161

#    api:
#        hostname: api
#        image: registry.cn-shanghai.aliyuncs.com/jext/starter_api:latest
#        restart: always
##        volumes:
##            - ../data/files:/tmp/files
#        ports:
#            - 8011:8011
#        depends_on:
#            - db
#            - cache
#            - mq

#    srv:
#        image: starter_service:latest
#        build:
#          context: .
#          dockerfile: Dockerfile_ce
#        restart: always
#        ports:
#            - 8001:8001
#        depends_on:
#          - cache
#          - mq
#
#    mq_consumer:
#        image: starter_service:latest
#        command: python manage.py mq
#        restart: always
#        depends_on:
#            - cache
#            - mq
#
#    task:
#        image: starter_service:latest
#        command: celery -A starter_service worker -l info
#        restart: always
#        depends_on:
#            - cache
#            - mq
#
#    task_viewer:
#        image: starter_service:latest
#        command: celery flower --broker=redis://cache:6379/2
#        restart: always
#        ports:
#            - 5555:5555
#        depends_on:
#            - task
